### ISSUE TITLE
Privacy popup shows up each time when shortcut is about to run

### ISSUE THREAD

**Issue by pradeepb28** [tigi44/SiriKitExample#1]
![CleanShot 2021-12-16 at 13 46 44](https://user-images.githubusercontent.com/6823101/146334152-65e1bfee-a30a-4026-89d1-f8a4bc362330.png)

Despite I allowed the privacy, the popup keeps showing up. Is there a way to turn it off?
Thanks for the tutorial!

**Comment by tigi44** [comment]
@pradeepb28 

Thank you for watching my code.
Considering that the app name in the privacy pop-up is null, the intents setting seems to be wrong.

In addition, it would be better to refer to the website below regarding the privacy pop-up.
- https://support.apple.com/guide/shortcuts/adjust-privacy-settings-apd961a4fc65/ios

**Comment by pradeepb28** [comment]
Thanks for replying but all I did was downloaded your repo and ran from Xcode 13.1 and used iOS 15 simulators.
